### ISSUE TITLE
Team-166

### ISSUE THREAD

**Issue by HillaryOkello** [Zappat0n/TNW-clone#2]
Set a maximum width for a tablet screen, and centre the main page content

**Comment by 0x1100010010** [comment]
Angel great work all around. Your code is structured on best practices, neat, clean, and easy to follow. As @HillaryOkello mentioned there are a few tweaks to make.

- Max width of all screens and content.
- Centring the whole body content (with exception of landing images on top )
- Minor adjustments in sections spacing.

And you are good to go!

**Comment by o-rashad** [comment]
All considerations are taken care of... 

Thank you 
@bashforger @HillaryOkello  <3
